name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: create a directory and save the build artifacts
        run:   mkdir out

      - name: copy build artifacts to out directory
        run:  cp target/*.jar out/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
            name: java-app
            path: out/*.jar

            
            
      - name: Check the content of target directory
        run:  ls -al out/
              
        

     

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: out/
        

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: java_app
          environment_name: java-app
          version_label: ${{ github.run_number }}
          region: us-east-1
          deployment_package: out/*.jar
          
          
