name: Build & Deploy Java App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # Change if needed

    - name: Build with Maven
      run: mvn clean package

    - name: Prepare deployment zip
      run: |
        mkdir deploy
        cp target/*.jar deploy/application.jar
        echo 'web: java -jar application.jar' > deploy/Procfile
        zip -r app.zip deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload zip to S3
      run: |
        aws s3 cp app.zip s3://${{ secrets.EB_S3_BUCKET }}/app-${{ github.run_number }}.zip

    - name: Create new Elastic Beanstalk app version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APP_NAME }} \
          --version-label v-${{ github.run_number }} \
          --source-bundle S3Bucket=${{ secrets.EB_S3_BUCKET }},S3Key=app-${{ github.run_number }}.zip

    - name: Initialize EB CLI and deploy
      run: |
          eb init your-app-name --platform "Java 17 running on 64bit Amazon Linux 2" --region us-east-1
          eb use java_backend
          eb deploy 
